---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-delployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:alpine
        env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
        ports:
        - name: http
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name:  jenkins-service
spec:
  selector:
    app:  jenkins
  type:  NodePort
  ports:
  - name: http
    port:  80
    targetPort:  8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - host: jenkins.local 
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-service
          servicePort: 80 
